#ifndef INTEROP_NAMES_H_INCLUDED
#define INTEROP_NAMES_H_INCLUDED
#include <Nodos/Types.h>

NOS_REGISTER_NAME(VulkanBufferToCUDABuffer)
NOS_REGISTER_NAME(InputBuffer)
NOS_REGISTER_NAME(OutputBuffer);

NOS_REGISTER_NAME(TextureToBuffer)
NOS_REGISTER_NAME(TextureFormatConverter)
NOS_REGISTER_NAME(Input)
NOS_REGISTER_NAME(Output)
NOS_REGISTER_NAME(OutputFormat)
NOS_REGISTER_NAME(FloatToIntFormat)
NOS_REGISTER_NAME(FloatToIntFormat_Pass)

NOS_REGISTER_NAME(InputTexture)
NOS_REGISTER_NAME(outputType)
NOS_REGISTER_NAME(DST_TEXTURE_UINT32)
NOS_REGISTER_NAME(DST_TEXTURE_UINT16)
NOS_REGISTER_NAME(DST_TEXTURE_UINT8)
NOS_REGISTER_NAME(DST_TEXTURE_INT32)
NOS_REGISTER_NAME(DST_TEXTURE_INT16)
NOS_REGISTER_NAME(DST_TEXTURE_INT8)

NOS_REGISTER_NAME(LinearToSRGB);
NOS_REGISTER_NAME(LinearToSRGB_Shader);
NOS_REGISTER_NAME(LinearToSRGB_Pass);

#endif //INTEROP_NAMES_H_INCLUDED